export default `<!DOCTYPE html><html lang="es" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Consumo de Agua</title>
  <base href="/consumo-agua-app/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!-- Bootstrap CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>body{font-family:Segoe UI,Roboto,Arial,sans-serif;background-color:#e3f2fd;color:#222;margin:0;padding-top:70px;min-height:100vh;display:flex;flex-direction:column}.navbar-utp{background:linear-gradient(90deg,#1976d2,#64b5f6);box-shadow:0 2px 8px #1976d214}.navbar-utp .navbar-brand,.navbar-utp .nav-link{color:#fff!important;font-weight:500;transition:color .2s}.navbar-utp .nav-link.active,.navbar-utp .nav-link:hover{color:#81d4fa!important;text-shadow:0 1px 2px rgba(25,118,210,.15)}.navbar-utp .navbar-brand i{margin-right:8px}.btn-main{background-color:#1976d2;color:#fff;border:none;border-radius:.25rem;padding:.5rem 1.2rem;transition:background .2s}.btn-main:hover,.btn-main:focus{background-color:#1565c0;color:#e3f2fd}.btn-main:disabled{background-color:#a0aec0;cursor:not-allowed}.card-main{border:1px solid #bbdefb;border-left:5px solid #1976d2;border-radius:.5rem;box-shadow:0 2px 8px #1976d20f;margin-bottom:1.5rem;background:#fff}.card-main .card-header{background-color:#1976d2;color:#fff;font-weight:600;border-bottom:1px solid #1565c0;border-radius:.5rem .5rem 0 0}.card-main .card-body{padding:1.25rem}.form-control:focus{border-color:#1976d2;box-shadow:0 0 0 .2rem #1976d226}@media (max-width: 600px){.card-main{margin:1rem .5rem}.navbar-utp .navbar-brand{font-size:1rem}}.main-content{flex:1 0 auto;padding:2rem 1rem;width:100%;max-width:900px;margin:0 auto}
</style><link rel="stylesheet" href="styles-HP6WMEX3.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-HP6WMEX3.css"></noscript></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","submit","input","compositionstart","compositionend","change"],["blur"]);</script>
  <app-root ng-version="19.2.14" ngh="2" ng-server-context="ssg"><app-navbar ngh="0"><nav class="navbar navbar-expand-lg navbar-utp fixed-top"><div class="container-fluid"><a href="#" class="navbar-brand d-flex align-items-center"><i class="fa fa-tint"></i><span class="ms-2">Consumo de Agua</span></a><button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button><div id="navbarNav" class="collapse navbar-collapse"><ul class="navbar-nav ms-auto"><li class="nav-item"><a routerlink="/meta" routerlinkactive="active" class="nav-link" href="/consumo-agua-app/meta" jsaction="click:;"><i class="fa fa-bullseye"></i> Meta diaria </a></li><li class="nav-item"><a routerlink="/registro" routerlinkactive="active" class="nav-link active" href="/consumo-agua-app/registro" jsaction="click:;"><i class="fa fa-plus-circle"></i> Registrar consumo </a></li><li class="nav-item"><a routerlink="/resumen" routerlinkactive="active" class="nav-link" href="/consumo-agua-app/resumen" jsaction="click:;"><i class="fa fa-table"></i> Resumen </a></li></ul></div></div></nav></app-navbar><router-outlet></router-outlet><app-formulario-registro ngh="1"><div class="main-content"><div class="card card-main mx-auto" style="max-width: 400px;"><div class="card-header"><i class="fa fa-plus-circle"></i> Registrar consumo de agua </div><div class="card-body"><form novalidate class="ng-untouched ng-pristine ng-invalid" jsaction="submit:;"><div class="mb-3"><label for="cantidad" class="form-label">Cantidad</label><input type="number" id="cantidad" name="cantidad" min="1" required class="form-control ng-untouched ng-pristine ng-invalid" value="0" jsaction="input:;blur:;compositionstart:;compositionend:;"></div><div class="mb-3"><label class="form-label">Unidad</label><select name="unidad" class="form-select ng-untouched ng-pristine ng-valid" jsaction="change:;blur:;"><option value="ml">Mililitros (ml)</option><option value="l">Litros (L)</option></select></div><button type="submit" class="btn btn-main w-100" disabled> Registrar consumo </button></form><!----></div></div></div></app-formulario-registro><!----><footer class="text-center text-lg-start bg-light text-muted mt-5"><div class="text-center p-4"> © 2023 Consumo de Agua. Todos los derechos reservados. </div></footer></app-root>
  <!-- Bootstrap JS Bundle CDN (incluye Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="polyfills-B6TNHZQ6.js" type="module"></script><script src="main-64THJ7JQ.js" type="module"></script>
<script id="ng-state" type="application/json">{"__nghData__":[{},{"t":{"22":"t0"},"c":{"22":[]}},{"c":{"1":[{"i":"c333424408","r":1}]}}]}</script></body></html>`;